# docker-compose.yml

services:
  web:
    platform: linux/amd64
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --reload --host 0.0.0.0'
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql+psycopg://fastapi_traefik:fastapi_traefik@db:5432/fastapi_traefik
    depends_on:
      - db
  db:
    platform: linux/amd64
    image: postgis/postgis
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=fastapi_traefik
      - POSTGRES_PASSWORD=fastapi_traefik
      - POSTGRES_DB=fastapi_traefik

volumes:
  postgres_data:
