# docker-compose.dev.yml
services:
  web:
    platform: linux/amd64
    build: .
    command: /upstream/scripts/run.sh --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg://fastapi_traefik:fastapi_traefik@disasterpostgres.pods.portals.tapis.io:443/fastapi_traefik?sslmode=require}
