#!/usr/bin/env python3
"""
Register or update an Upstream OAuth2 client on a Tapis tenant.

Tapis stores callback_url as a single string — only one URL per client.
Each environment needs its own client:

    upstream-develop  → https://upstreamdevelop.pods.portals.tapis.io/callback
    upstream-prod     → https://upstream.pods.portals.tapis.io/callback
    upstream-local    → http://localhost:3000/callback

Usage:
    export TAPIS_USERNAME=<your-username>
    export TAPIS_PASSWORD=<your-password>
    python3 scripts/create_oauth_client.py

Optional env vars (defaults shown):
    TAPIS_BASE_URL=https://portals.tapis.io
    CLIENT_ID=upstream-develop
    CLIENT_KEY=<auto-generated secure random string>
    CALLBACK_URL=https://upstreamdevelop.pods.portals.tapis.io/callback
"""
import os
import sys
import time
import secrets
import requests
from tapipy.tapis import Tapis

BASE_URL = os.environ.get("TAPIS_BASE_URL", "https://portals.tapis.io")
CLIENT_ID = os.environ.get("CLIENT_ID", "upstream-develop")
CLIENT_KEY = os.environ.get("CLIENT_KEY") or secrets.token_urlsafe(32)
CALLBACK_URL = os.environ.get(
    "CALLBACK_URL",
    "https://upstreamdevelop.pods.portals.tapis.io/callback",
)


def print_result(result, client_id, client_key, callback_url):
    print()
    print("=" * 60)
    print(f"  client_id:    {result.get('client_id', client_id)}")
    print(f"  client_key:   {client_key}")
    print(f"  callback_url: {result.get('callback_url', callback_url)}")
    print("=" * 60)
    print()
    print(f"  VITE_TAPIS_OAUTH_CLIENT_ID={client_id}")
    print(f"  VITE_TAPIS_OAUTH_CLIENT_KEY={client_key}")


# ---------------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------------
print(f"Authenticating as {os.environ['TAPIS_USERNAME']} to {BASE_URL} ...")
t = Tapis(base_url=BASE_URL, username=os.environ["TAPIS_USERNAME"], password=os.environ["TAPIS_PASSWORD"])
t.get_tokens()
token = t.access_token.access_token
print("Token acquired.\n")

headers = {
    "X-Tapis-Token": token,
    "Content-Type": "application/json",
    "Accept": "application/json",
}

payload = {
    "client_id": CLIENT_ID,
    "client_key": CLIENT_KEY,
    "callback_url": CALLBACK_URL,
    "display_name": "Upstream UI",
    "description": "Upstream data platform unified UI — authorization code flow",
}

print(f"  client_id:    {CLIENT_ID}")
print(f"  callback_url: {CALLBACK_URL}")
print()

# ---------------------------------------------------------------------------
# Try PUT update first (avoids DELETE consistency lag; works on inactive clients)
# ---------------------------------------------------------------------------
r = requests.get(f"{BASE_URL}/v3/oauth2/clients/{CLIENT_ID}", headers=headers, timeout=30)
if r.ok:
    existing = r.json().get("result", {})
    print(f"Client '{CLIENT_ID}' exists — updating via PUT ...")
    print(f"  Old callback_url: {existing.get('callback_url')}")

    put_r = requests.put(
        f"{BASE_URL}/v3/oauth2/clients/{CLIENT_ID}",
        headers=headers,
        json=payload,
        timeout=30,
    )
    if put_r.ok:
        print_result(put_r.json().get("result", {}), CLIENT_ID, CLIENT_KEY, CALLBACK_URL)
        sys.exit(0)

    print(f"  PUT returned {put_r.status_code}: {put_r.text}")
    print("  Falling back to DELETE + POST ...")

    d = requests.delete(f"{BASE_URL}/v3/oauth2/clients/{CLIENT_ID}", headers=headers, timeout=30)
    if not d.ok:
        print(f"  ERROR deleting client {d.status_code}: {d.text}")
        sys.exit(1)
    print("  Deleted.\n")

# ---------------------------------------------------------------------------
# POST (create)
# ---------------------------------------------------------------------------
print(f"Creating OAuth2 client '{CLIENT_ID}' ...")

r = None
for attempt in range(1, 25):
    r = requests.post(f"{BASE_URL}/v3/oauth2/clients", headers=headers, json=payload, timeout=30)
    if r.ok:
        break
    if "already exists" in r.text.lower() or "uniqueness" in r.text.lower():
        print(f"  (attempt {attempt}/24) Tapis still has old record — waiting 5s ...")
        time.sleep(5)
        continue
    print(f"ERROR {r.status_code}: {r.text}")
    sys.exit(1)

if not r or not r.ok:
    print("ERROR: client still exists after 2 minutes of retries.")
    print("Wait 30 seconds and try again, or choose a different CLIENT_ID.")
    sys.exit(1)

print_result(r.json().get("result", {}), CLIENT_ID, CLIENT_KEY, CALLBACK_URL)
