#!/usr/bin/env python3
"""
Register the upstream-ui OAuth2 client on a Tapis tenant.

Creates (or reports on) the client that the unified UI uses for the
authorization-code login flow.  Run this once per tenant before the
OAuth2 login button will work.

Usage:
    export TAPIS_USERNAME=<your-username>
    export TAPIS_PASSWORD=<your-password>
    python3 scripts/create_oauth_client.py

Optional env vars (defaults shown):
    TAPIS_BASE_URL=https://portals.tapis.io
    CLIENT_ID=upstream-ui
    CLIENT_KEY=<auto-generated secure random string>
    CALLBACK_URLS=<comma-separated list>   # see DEFAULT_CALLBACKS below
"""
import os
import sys
import secrets
import requests
from tapipy.tapis import Tapis

BASE_URL = os.environ.get("TAPIS_BASE_URL", "https://portals.tapis.io")
CLIENT_ID = os.environ.get("CLIENT_ID", "upstream-ui")
CLIENT_KEY = os.environ.get("CLIENT_KEY") or secrets.token_urlsafe(32)

DEFAULT_CALLBACKS = ",".join([
    # develop pod
    "https://upstreamdevelop.pods.portals.tapis.io/callback",
    # local Vite dev server (common ports)
    "http://localhost:5173/callback",
    "http://localhost:5174/callback",
    # production pod (add when ready)
    # "https://upstream.pods.portals.tapis.io/callback",
])
CALLBACK_URLS = os.environ.get("CALLBACK_URLS", DEFAULT_CALLBACKS)

# ---------------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------------
print(f"Authenticating as {os.environ['TAPIS_USERNAME']} to {BASE_URL} ...")
t = Tapis(base_url=BASE_URL, username=os.environ["TAPIS_USERNAME"], password=os.environ["TAPIS_PASSWORD"])
t.get_tokens()
token = t.access_token.access_token
print("Token acquired.\n")

headers = {
    "X-Tapis-Token": token,
    "Content-Type": "application/json",
    "Accept": "application/json",
}

# ---------------------------------------------------------------------------
# Check if client already exists
# ---------------------------------------------------------------------------
r = requests.get(f"{BASE_URL}/v3/oauth2/clients/{CLIENT_ID}", headers=headers, timeout=30)
if r.ok:
    existing = r.json().get("result", {})
    print(f"Client '{CLIENT_ID}' already exists:")
    print(f"  client_id:    {existing.get('client_id')}")
    print(f"  callback_url: {existing.get('callback_url')}")
    print(f"  display_name: {existing.get('display_name')}")
    print()
    print("To add new redirect URIs, delete and recreate:")
    print(f"  DELETE {BASE_URL}/v3/oauth2/clients/{CLIENT_ID}")
    print("Then re-run this script with CALLBACK_URLS set to the full list.")
    sys.exit(0)

# ---------------------------------------------------------------------------
# Create client
# ---------------------------------------------------------------------------
print(f"Creating OAuth2 client '{CLIENT_ID}' ...")
print(f"  Callback URLs: {CALLBACK_URLS}")
print()

payload = {
    "client_id": CLIENT_ID,
    "client_key": CLIENT_KEY,
    "callback_url": CALLBACK_URLS,
    "display_name": "Upstream UI",
    "description": "Upstream data platform unified UI — authorization code flow",
}

r = requests.post(f"{BASE_URL}/v3/oauth2/clients", headers=headers, json=payload, timeout=30)
if not r.ok:
    print(f"ERROR {r.status_code}: {r.text}")
    sys.exit(1)

result = r.json().get("result", {})
print("Created successfully!")
print()
print("=" * 60)
print(f"  client_id:    {result.get('client_id', CLIENT_ID)}")
print(f"  client_key:   {CLIENT_KEY}")
print(f"  callback_url: {result.get('callback_url', CALLBACK_URLS)}")
print("=" * 60)
print()
print("Set this in your environment / pod config:")
print(f"  VITE_TAPIS_OAUTH_CLIENT_ID={CLIENT_ID}")
print()
print("If Tapis requires the client_key in the token-exchange request")
print("(check: does /callback fail with 'invalid client'?), also set:")
print(f"  VITE_TAPIS_OAUTH_CLIENT_KEY={CLIENT_KEY}")
print("and update exchangeOAuthCode() in tapisAuth.ts to include it.")
