#!/usr/bin/env python3
"""
Register or update the upstream-ui OAuth2 client on a Tapis tenant.

If the client already exists it is deleted and recreated with the current
callback URL list (idempotent update).

Usage:
    export TAPIS_USERNAME=<your-username>
    export TAPIS_PASSWORD=<your-password>
    python3 scripts/create_oauth_client.py

Optional env vars (defaults shown):
    TAPIS_BASE_URL=https://portals.tapis.io
    CLIENT_ID=upstream-ui
    CLIENT_KEY=<auto-generated secure random string>
    CALLBACK_URLS=<comma-separated list>   # see DEFAULT_CALLBACKS below
"""
import os
import sys
import time
import secrets
import requests
from tapipy.tapis import Tapis

BASE_URL = os.environ.get("TAPIS_BASE_URL", "https://portals.tapis.io")
CLIENT_ID = os.environ.get("CLIENT_ID", "upstream-ui")
CLIENT_KEY = os.environ.get("CLIENT_KEY") or secrets.token_urlsafe(32)

DEFAULT_CALLBACKS = ",".join([
    # deployed pods
    "https://upstreamdevelop.pods.portals.tapis.io/callback",
    "https://upstream.pods.portals.tapis.io/callback",
    # local dev servers (common ports)
    "http://localhost:3000/callback",
    "http://localhost:5173/callback",
    "http://localhost:5174/callback",
])
CALLBACK_URLS = os.environ.get("CALLBACK_URLS", DEFAULT_CALLBACKS)

# ---------------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------------
print(f"Authenticating as {os.environ['TAPIS_USERNAME']} to {BASE_URL} ...")
t = Tapis(base_url=BASE_URL, username=os.environ["TAPIS_USERNAME"], password=os.environ["TAPIS_PASSWORD"])
t.get_tokens()
token = t.access_token.access_token
print("Token acquired.\n")

headers = {
    "X-Tapis-Token": token,
    "Content-Type": "application/json",
    "Accept": "application/json",
}

# ---------------------------------------------------------------------------
# Delete existing client if present (so we can recreate with updated URLs)
# ---------------------------------------------------------------------------
r = requests.get(f"{BASE_URL}/v3/oauth2/clients/{CLIENT_ID}", headers=headers, timeout=30)
if r.ok:
    existing = r.json().get("result", {})
    print(f"Client '{CLIENT_ID}' exists — deleting to recreate with updated callback URLs.")
    print(f"  Old callback_url: {existing.get('callback_url')}")
    d = requests.delete(f"{BASE_URL}/v3/oauth2/clients/{CLIENT_ID}", headers=headers, timeout=30)
    if not d.ok:
        print(f"  ERROR deleting client {d.status_code}: {d.text}")
        sys.exit(1)
    print("  Deleted.\n")

# ---------------------------------------------------------------------------
# Create client
# ---------------------------------------------------------------------------
print(f"Creating OAuth2 client '{CLIENT_ID}' ...")
print(f"  Callback URLs:")
for url in CALLBACK_URLS.split(","):
    print(f"    {url.strip()}")
print()

payload = {
    "client_id": CLIENT_ID,
    "client_key": CLIENT_KEY,
    "callback_url": CALLBACK_URLS,
    "display_name": "Upstream UI",
    "description": "Upstream data platform unified UI — authorization code flow",
}

# Retry with backoff — Tapis delete is not immediately consistent.
r = None
for attempt in range(1, 7):
    r = requests.post(f"{BASE_URL}/v3/oauth2/clients", headers=headers, json=payload, timeout=30)
    if r.ok:
        break
    if "already exists" in r.text.lower() or "uniqueness" in r.text.lower():
        print(f"  (attempt {attempt}/6) Tapis still has the old record — waiting 3s ...")
        time.sleep(3)
        continue
    print(f"ERROR {r.status_code}: {r.text}")
    sys.exit(1)

if not r or not r.ok:
    print(f"ERROR: client still exists after 6 attempts. Try again in a few seconds.")
    sys.exit(1)

result = r.json().get("result", {})
print("Created successfully!")
print()
print("=" * 60)
print(f"  client_id:    {result.get('client_id', CLIENT_ID)}")
print(f"  client_key:   {CLIENT_KEY}")
print(f"  callback_url: {result.get('callback_url', CALLBACK_URLS)}")
print("=" * 60)
print()
print("Set this in your environment / pod config:")
print(f"  VITE_TAPIS_OAUTH_CLIENT_ID={CLIENT_ID}")
print()
print("If Tapis requires the client_key in the token-exchange request")
print("(check: does /callback fail with 'invalid client'?), also set:")
print(f"  VITE_TAPIS_OAUTH_CLIENT_KEY={CLIENT_KEY}")
print("and update exchangeOAuthCode() in tapisAuth.ts to include it.")
